### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/minecraft/render/tmpwqwyymrh'

### ISSUE THREAD

**Issue by AugusDogus** [mide/minecraft-overviewer#48]
When running the docker image with the following run statement:

```docker pull mide/minecraft-overviewer:latest
docker run \
  --rm \
  -e MINECRAFT_VERSION="1.15.2" \
  -v /opt/minecaft/compatibility_issues:/home/minecraft/server/:ro \
  -v /opt/minecraft/overviewer:/home/minecraft/render/:rw \
  mide/minecraft-overviewer:latest
```

I get the following error:

```2020-01-26 20:23:41 (106 MB/s) - '1.15.2.jar' saved [15531492/15531492]

2020-01-26 20:23:42  Welcome to Minecraft Overviewer!
*******************************************************************************
2020-01-26 20:23:42 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 650, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 443, in main
    assetMrg = assetmanager.AssetManager(destdir, config.get('customwebassets', None))
  File "/usr/lib/python3.5/dist-packages/overviewer_core/assetmanager.py", line 47, in __init__
    self.fs_caps = get_fs_caps(self.outputdir)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/files.py", line 27, in get_fs_caps
    return {"chmod_works": does_chmod_work(dir_to_test),
  File "/usr/lib/python3.5/dist-packages/overviewer_core/files.py", line 38, in does_chmod_work
    f1 = tempfile.NamedTemporaryFile(dir=dir_to_test)
  File "/usr/lib/python3.5/tempfile.py", line 688, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.5/tempfile.py", line 399, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/home/minecraft/render/tmpwqwyymrh'```

**Comment by AugusDogus** [comment]
I should note that this error happens both when I create the directory `/opt/minecraft/overviewer` before I run the docker run command and when I let the container create the directory itself.

I was able to temporarily get the container working by doing `chmod -R 0755 /opt/minecraft/overviewer`, but I am looking for a better solution.

**Comment by AugusDogus** [comment]
I mispelled minecraft as minecaft. 🙃 Ignore.
