### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by nicobleiler** [mide/minecraft-overviewer#71]
2020-05-22 16:04:27 (10.0 MB/s) - '/home/minecraft/.minecraft/versions/1.15.2/1.15.2.jar' saved [15531492/15531492]

2020-05-22 16:04:27  Welcome to Minecraft Overviewer!
*******************************************************************************
2020-05-22 16:04:27 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 650, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 443, in main
    assetMrg = assetmanager.AssetManager(destdir, config.get('customwebassets', None))
  File "/usr/lib/python3.5/dist-packages/overviewer_core/assetmanager.py", line 47, in __init__
    self.fs_caps = get_fs_caps(self.outputdir)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/files.py", line 27, in get_fs_caps
    return {"chmod_works": does_chmod_work(dir_to_test),
  File "/usr/lib/python3.5/dist-packages/overviewer_core/files.py", line 38, in does_chmod_work
    f1 = tempfile.NamedTemporaryFile(dir=dir_to_test)
  File "/usr/lib/python3.5/tempfile.py", line 688, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.5/tempfile.py", line 399, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/home/minecraft/render/tmp93nlol0v'

**Comment by mide** [comment]
Can you try the tips referenced in this comment? https://github.com/mide/minecraft-overviewer/issues/51#issuecomment-624988309 - I haven't had a chance to update the documentation yet.

**Comment by yasiupl** [comment]
Same issue here, I'm not quite sure how to apply the `chown` fix. I'm not very familiar with docker.

**Comment by mide** [comment]
Yeah, I need to update the documentation - I'll see if I can get to it this weekend. I've had a lot going on so it's a bit tough to find time.

**Comment by yasiupl** [comment]
This solved my issue temporarily:
https://github.com/mide/minecraft-overviewer/issues/51#issuecomment-624988309

It so happens that I host my map under /var/www/ and I don't quite know what permissions to set so that both nginx and docker can read/write there.

**Comment by mide** [comment]
I will update the documentation as part of #72.
