### ISSUE TITLE
Permissions error with sample command

### ISSUE THREAD

**Issue by magneticflux-** [mide/minecraft-overviewer#8]
Log:
```
2018-04-22T17:27:59.024590033Z 2018-04-22 17:27:59 (670 KB/s) - '/home/minecraft/.minecraft/versions/1.12.2/1.12.2.jar' saved [10180113/10180113]
2018-04-22T17:27:59.024603027Z
2018-04-22T17:27:59.152183651Z 2018-04-22 17:27:59  Welcome to Minecraft Overviewer!
2018-04-22T17:27:59.153658711Z *******************************************************************************
2018-04-22T17:27:59.153688077Z 2018-04-22 17:27:59 E An error has occurred. This may be a bug. Please let us know!
2018-04-22T17:27:59.153701987Z See http://docs.overviewer.org/en/latest/index.html#help
2018-04-22T17:27:59.153708137Z
2018-04-22T17:27:59.153713429Z This is the error that occurred:
2018-04-22T17:27:59.153719518Z Traceback (most recent call last):
2018-04-22T17:27:59.153724837Z   File "/usr/bin/overviewer.py", line 624, in <module>
2018-04-22T17:27:59.153730905Z     ret = main()
2018-04-22T17:27:59.153736217Z   File "/usr/bin/overviewer.py", line 427, in main
2018-04-22T17:27:59.153741710Z     assetMrg = assetmanager.AssetManager(destdir, config.get('customwebassets', None))
2018-04-22T17:27:59.153747293Z   File "/usr/lib/python2.7/dist-packages/overviewer_core/assetmanager.py", line 47, in __init__
2018-04-22T17:27:59.153752930Z     self.fs_caps = get_fs_caps(self.outputdir)
2018-04-22T17:27:59.153758513Z   File "/usr/lib/python2.7/dist-packages/overviewer_core/files.py", line 27, in get_fs_caps
2018-04-22T17:27:59.153774017Z     return {"chmod_works": does_chmod_work(dir_to_test),
2018-04-22T17:27:59.153793604Z   File "/usr/lib/python2.7/dist-packages/overviewer_core/files.py", line 38, in does_chmod_work
2018-04-22T17:27:59.153799338Z     f1 = tempfile.NamedTemporaryFile(dir=dir_to_test)
2018-04-22T17:27:59.153804671Z   File "/usr/lib/python2.7/tempfile.py", line 475, in NamedTemporaryFile
2018-04-22T17:27:59.153810212Z     (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
2018-04-22T17:27:59.153815512Z   File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
2018-04-22T17:27:59.153820980Z     fd = _os.open(file, flags, 0600)
2018-04-22T17:27:59.153826316Z OSError: [Errno 13] Permission denied: '/home/minecraft/render/tmp8aeEXv'
```
Command:
```
docker run -v /mc/data/worldNew:/home/minecraft/server/world/:ro -v /mc/overviewer/worldNew:/home/minecraft/render/:rw -e MINECRAFT_VERSION=1.12.2 mide/minecraft-overviewer:latest
```

**Comment by mide** [comment]
Thank you for your report; I'll take a look at this as soon as I can.

**Comment by magneticflux-** [comment]
It turned out to be an error with the way Docker mounts volumes from the host. The location of my server data was not accessible by the container, so I had to `chown` and `chmod` them first.

**Comment by mide** [comment]
Oh, fantastic. Thanks for looking into that. Yeah, Docker mounts can be tricky with permissions.
