### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\User\\Desktop\\map\\world-lighting\\blank.png'

### ISSUE THREAD

**Issue by Paic26** [mide/minecraft-overviewer#97]
I keep getting this error, i don´t know whats wrong

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 653, in <module>
  File "overviewer.py", line 578, in main
  File "overviewer_core\assetmanager.py", line 76, in initialize
  File "overviewer_core\assetmanager.py", line 150, in _output_assets
  File "PIL\Image.py", line 1932, in save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\User\\Desktop\\map\\world-lighting\\blank.png'

**Comment by mide** [comment]
I need to add some documentation around permissions. I filed #72 a bit ago, but haven't had the time to do it. [This comment](https://github.com/mide/minecraft-overviewer/issues/51#issuecomment-624988309) seemed to help some folks.

**Comment by mide** [comment]
Closing in favor of #72.
